# 异常

由于发生异常，任务可能会失败。当你的RQ worker在后台运行时，你如何得到这些异常的通知？

## 默认： `FailedJobRegistry`

RQ的默认安全网是`FailedJobRegistry`。每个未成功执行的任务都会存储在此处，以及其异常信息（类型，值，回溯）。虽然这可以确保没有失败的任务“迷路”，但是主动得到关于任务失败的通知没有的。

## 自定义异常处理

RQ支持注册自定义异常处理程序。这样就可以将自己的错误处理逻辑注入到worker身上。

这是你将自定义异常处理程序注册到RQ worker的方法：

```python
from exception_handlers import foo_handler, bar_handler

w = Worker([q], exception_handlers=[foo_handler, bar_handler])
```

句柄本身是一个函数，采用下列参数：`job`， `exc_type`，`exc_value`和`traceback`：

```python
def my_handler(job, exc_type, exc_value, traceback):
    # 自定义事情
    # 例如, 写入异常到数据库中
```

你可能还会看到三个异常参数编码为：

```python
def my_handler(job, *exc_info):
    # do custom things here
from exception_handlers import foo_handler

w = Worker([q], exception_handlers=[foo_handler],
           disable_default_exception_handler=True)
```

## 链接异常处理

处理程序本身负责决定是否完成异常处理，或者应该落到堆栈上的下一个处理程序。处理程序可以通过返回布尔值来指示这一点。`False`表示停止处理异常，`True`表示继续并进入堆栈的下一个异常处理程序。

重要的是要知道实现者，默认情况下，当处理程序没有显式返回值（`None`）时，这将被解释为`True`（即继续使用下一个处理程序）。

防止处理程序链中的下一个异常处理程序执行，请使用不会丢失的自定义异常处理程序，例如：

```python
def black_hole(job, *exc_info):
    return False
```

